Repository hmrc/income-tax-view-change-frontend, pull requests merged in 2018-02, with the labels that each got.

#257 [BTAT-1467-Story] Deduct TaxableDividends from TotalTaxableIncome
  app/models/CalculationDataResponseModel.scala
  app/views/helpers/calcBreakdownHelper.scala.html
  it/controllers/CalculationControllerISpec.scala
  test/views/CrystallisedViewSpec.scala
  test/views/EstimatedTaxLiabilityViewSpec.scala
Labels: Demoed

#263 [BTAT-1476] updated content for IT landing page
  conf/messages
  test/assets/Messages.scala
Labels: Ready for Demo

#266 [BTAT-1793] updated calculationDataModel field name
  app/models/CalculationDataResponseModel.scala
  it/helpers/IntegrationTestConstants.scala
  test/assets/TestConstants.scala
Labels: PR1

#267 Btat 1799
  app/models/CalculationDataResponseModel.scala
  it/helpers/IntegrationTestConstants.scala
  test/assets/TestConstants.scala
Labels: PR2

#255 [BTAT-1486-Story] Use Accounting Period from Property Details Response
  app/config/features/Features.scala
  app/config/features/Keys.scala
  app/connectors/PropertyDetailsConnector.scala
  app/testOnly/controllers/FeatureSwitchController.scala
  app/testOnly/forms/FeatureSwitchForm.scala
  app/testOnly/models/FeatureSwitchModel.scala
  app/testOnly/views/featureSwitch.scala.html
  conf/application.conf
  it/helpers/IntegrationTestConstants.scala
  test/connectors/PropertyDetailsConnectorSpec.scala
Labels: Demoed
